### ISSUE TITLE
请问这个工具如何安装使用，fiss命令无法识别，win10系统

### ISSUE THREAD

**Issue by lbb00** [fiss-scaffold/fiss-command-release#1]
npm install -g fiss-command-release或是安装到项目里，fiss命令不能识别，在网上查了一下是不是因为fiss-command-release的package.json里需要设置bin:{fiss: "xxx.js"}这样，能帮忙解决一下么

**Comment by zhangyihua** [comment]
这个是 [fiss](https://github.com/zhangyihua/fiss) 的一个定制插件，请配合 fiss 使用

**Comment by lbb00** [comment]
thanks

**Comment by zhangyihua** [comment]
我现在还不太明白你的使用场景。请问你是单独使用的吗? 这个工具不能单独使用。 [fiss](https://github.com/zhangyihua/fiss) 默认依赖 fiss-command-release ，安装 fiss 的时候会自动安装。请参考一下 [fiss](https://github.com/zhangyihua/fiss)，如果你是配合 [fis3](http://fis.baidu.com/fis3/index.html) 使用，那么参考 fis3 的相关配置方法，让 fis3 能够识别 fiss 前缀的插件。
